from common.waf import cmd_configure as configure
from common.waf import cmd_build as doc_build
from common.waf import cmd_options as options
from common.waf import spell
from common.waf import cmd_spell
from common.waf import linkcheck
from common.waf import cmd_linkcheck

import posix_md

def gen_posix_md(task):
    c = posix_md.compliance()
    c.load(task.inputs[1].abspath())
    s = ['']
    for standard in posix_md.standards:
        s += ['% SPDX-License-Identifier: CC-BY-SA-4.0',
              '',
              '# {}'.format(posix_md.standard_names[standard]),
               ''] + c.output(standard)
    with open(task.outputs[0].abspath(), 'w') as w:
        from os import linesep
        w.write(linesep.join(s))

def build(ctx):
    ctx(rule = gen_posix_md,
        source = ['posix_md.py', 'RTEMS-Standards-Compliance.csv'],
        target = 'generated-posix-compliance.md')
    sources = { 'extra' : ['generated-posix-compliance.md'] }
    doc_build(ctx, sources = sources)
