from sys import path
from os.path import abspath
path.insert(0, abspath('../common/'))

from waf import cmd_configure as configure
from waf import cmd_build_images as build
from waf import cmd_options as options
