from sys import path
from os.path import abspath
path.append(abspath('../common/'))

from waf import cmd_options_path, cmd_configure_path, cmd_build_path, spell, cmd_spell


def options(ctx):
		cmd_options_path(ctx)

def configure(ctx):
	cmd_configure_path(ctx)

def build(ctx):
	cmd_build_path(ctx)

