' SPDX-License-Identifier: CC-BY-SA-4.0

' Copyright (C) 2019 embedded brains GmbH

@startuml

start

repeat
  :Invoke: ""doorstop edit REQ"";

  note right
    For this activity the UID
    of the requirement shall be REQ.
    It is located in a file REQ.yml.
  end note

  :Edit the requirement according to your needs and save it;

  :Commit REQ.yml with a proper message;

  :Send the patch to the devel@rtems.org mailing list for review;
repeat while (Reviewers demand changes in the modified requirement?) is (Yes)
->No;

if (Modified requirement was accepted by reviewers?) then (Yes)
  :Push the commit to the project repository;
else (No)
  :Keep the requirement as is;
endif

stop

@enduml
