' SPDX-License-Identifier: CC-BY-SA-4.0

' Copyright (C) 2019, 2020 embedded brains GmbH & Co. KG

@startuml

start

repeat
  :Edit: ""spec/component/req.yml"";

  note right
    For this activity the UID of the
    requirement shall be spec:/component/req.
    It is located in a file spec/component/req.yml.
  end note

  :Edit the attributes according to your needs and save the file;

  :Commit the changes with a proper message;

  :Send the patch to the devel@rtems.org mailing list for review;
repeat while (Reviewers demand changes in the modified requirement?) is (Yes)
->No;

if (Modified requirement was accepted by reviewers?) then (Yes)
  :Push the commit to the project repository;
else (No)
  :Keep the requirement as is;
endif

stop

@enduml
