' SPDX-License-Identifier: CC-BY-SA-4.0

' Copyright (C) 2019 embedded brains GmbH

@startuml

start

:Invoke: ""doorstop add RTEMS"";

note right
  This will create a new requirement.
  For this activity its UID shall be NEW.
  It is located in a file NEW.yml.
end note

while (Needs a link to a parent requirement?) is (Yes)
  :Invoke: ""doorstop link NEW PARENT"";
endwhile (No)

repeat
  :Invoke: ""doorstop edit NEW"";

  :Edit the requirement according to your needs and save it;

  :Commit NEW.yml with a proper message;

  :Send the patch to the devel@rtems.org mailing list for review;
repeat while (Reviewers demand changes in the new requirement?) is (Yes)
->No;

if (New requirement was accepted by reviewers?) then (Yes)
  :Push the commit to the project repository;
else (No)
  :Discard the NEW requirement;
endif

stop

@enduml
